apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbdemo
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: sbdemo
          resources:
            limits:
              memory: 250Mi
            requests:
              memory: 125Mi
          env:
          - name: MEM_TOTAL_MB
            valueFrom:
              resourceFieldRef:
                resource: limits.memory
