apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-configmap
data:
  application-prod.yml: |
    management:
      health:
        probes:
          enabled: true
      endpoints:
        web:
          exposure:
            include: "*"
      metrics:
        tags:
          application: ${spring.application.name}
    logging:
      level:
        root: debug
      path: ${LOG_HOME:/tmp/logs}
    spring:
      datasource:
        poolName: demo-pool
        autoCommit: false
    giltab:
      url: 128.195.53.249
      token: ${PRIVATE-TOKEN:123456789}
