apiVersion: v1
data:
  application-prod.properties: |
    spring.jpa.hibernate.ddl-auto=update
    spring.datasource.url=jdbc:mysql://<prod_database_host>:3306/db_example
    spring.datasource.username=root
    spring.datasource.password=admin
  application.properties: |
    app.name=Kustomize Demo
kind: ConfigMap
metadata:
  labels:
    env: prod
  name: prod-demo-configmap-57kt22m6bh
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sbdemo
    env: prod
  name: prod-sbdemo
spec:
  ports:
  - port: 8080
  selector:
    app: sbdemo
    env: prod
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sbdemo
    env: prod
  name: prod-sbdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sbdemo
      env: prod
  template:
    metadata:
      labels:
        app: sbdemo
        env: prod
    spec:
      containers:
      - env:
        - name: MEM_TOTAL_MB
          valueFrom:
            resourceFieldRef:
              resource: limits.memory
        - name: spring.profiles.active
          value: prod
        image: jingfang/sbdemo
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 3
        name: sbdemo
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/info
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
        resources:
          limits:
            memory: 1250Mi
          requests:
            memory: 1250Mi
        volumeMounts:
        - mountPath: /config
          name: demo-config
      volumes:
      - configMap:
          name: prod-demo-configmap-57kt22m6bh
        name: demo-config
