apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
configMapGenerator:
- files:
  - application.yml
  name: demo-configmap
patches:
- path: patch.yaml
  target:
    group: apps
    kind: Deployment
    name: sbdemo
    version: v1
- path: memorylimit_patch.yaml
  target:
    group: apps
    kind: Deployment
    name: sbdemo
    version: v1
- path: healthcheck_patch.yaml
  target:
    group: apps
    kind: Deployment
    name: sbdemo
    version: v1
namePrefix: prod-
commonLabels:
  env: prod
